### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by yangyuimmerse** [anitarau/Stereo_matching#2]
I am having a problem when I run your code(stereoMatchingPredict.py) like 250 left_resized = tf.image.resize_images(left,resize_shape),Type:Error:Expected binary or unicode string,got array。。。
If you can help solve it, be grateful.

**Comment by anitarau** [comment]
Can you provide the entire error message? Might be a version problem (Think I used 1.2.0). Try to find out what input tf.image.resize_images expects. Maybe the function was changed.

**Comment by yangyuimmerse** [comment]
I'm glad to see your reply，This error has been solved，Because there is something wrong with the input data，But the result is not as ideal as in the paper。I  can't find the reason Temporarily
[result.zip](https://github.com/anitarau/Stereo_matching/files/2388163/result.zip)

**Comment by anitarau** [comment]
Sorry to hear that. Is that when you train the model or have you also tried to just load my weights?

**Comment by yangyuimmerse** [comment]
I like your work very much, but I can't repeat it. Use your weight, but also no good results.
